#pragma once
//#define _RandOBJ
//#define _SPACESHIP
//#define _TESTBLOCK
#define _Billboard
#define _NENE
#define _MECHAGIRL
//#define _GIRL
//#define _REFLECT
//#define _EnviornmentMap
#define _SPONZA
#define _HOUSE
#define _NORMALMAP
#define _MutantWalk
#define _Praying
#define _Herald
//#define _DRAGON
//#define _MoveDirecionalLight