#pragma once
//#define _SPACESHIP
//#define _TESTBLOCK
//#define _NENE
//#define _MECHAGIRL
#define _GIRL
//#define _REFLECT
//#define _EnviornmentMap
//#define _SPONZA
//#define _HOUSE
//#define _NORMALMAP
#define _MoveDirecionalLight