#pragma once
#define _DebugRender
#define _Floor
#define _RandOBJ
#define _Billboard
#define _NENE
#define _EnviornmentMap
#define _HOUSE
#define _SPONZA
#define _NORMALMAP
#define _MutantWalk
#define _Praying
#define _Herald		
#define _Doro
#define _GeoSphere
//#define _Rapunzel
//#define _Zhao
//#define _DRAGON
//#define _MoveDirecionalLight
//#define _REFLECT
//#define _MECHAGIRL
//#define _GIRL

//#define _SPACESHIP
//#define _TESTBLOCK